language: python
dist: xenial
python: '3.7.4'
cache: false

env:
  global:
    - PYTEST_ADDOPTS="-ra -vv --durations=50"
    - PIP_DISABLE_PIP_VERSION_CHECK=1

# setuptools-scm needs all tags in order to obtain a proper version
git:
  depth: false

install:
  - python -m pip install git+https://github.com/blueyed/tox@master

jobs:
  include:
    # Coverage for Python 3.5.{0,1} specific code, mostly typing related.
    - env:
        - TOXENV=py35-coverage
        - PYTEST_ADDOPTS="-k 'test_raises_cyclic_reference or test_supports_breakpoint_module_global'"
      python: '3.5.1'
      dist: trusty
      before_install:
        - python -m pip install -U pip==19.3.1
        # Work around https://github.com/jaraco/zipp/issues/40.
        - python -m pip install -U 'setuptools>=34.4.0' virtualenv

before_script:
  - python -m tox --notest -v --durations

script:
  - env COLUMNS=130 python -m tox -v --durations
  - env CODECOV_NAME="$TOXENV-$TRAVIS_OS_NAME" scripts/report-coverage.sh -F Travis

branches:
  only:
    - my-master
