language: python
dist: xenial
stages:
- baseline
- name: test
  if: repo = pytest-dev/pytest AND tag IS NOT present
- name: deploy
  if: repo = pytest-dev/pytest AND tag IS present
python:
  - '3.7'
install:
  - python -m pip install --upgrade --pre tox

jobs:
  include:
    - env: TOXENV=docs

matrix:
  allow_failures:
    - python: '3.8-dev'
      env: TOXENV=py38-xdist

before_script:
  - |
    # Do not (re-)upload coverage with cron runs.
    if [[ "$TRAVIS_EVENT_TYPE" = cron ]]; then
      PYTEST_COVERAGE=0
    fi
  - |
    if [[ "$PYTEST_COVERAGE" = 1 ]]; then
      export COVERAGE_FILE="$PWD/.coverage"
      export COVERAGE_PROCESS_START="$PWD/.coveragerc"
      export _PYTEST_TOX_COVERAGE_RUN="coverage run -m"
      export _PYTEST_TOX_EXTRA_DEP=coverage-enable-subprocess
    fi

script: tox --recreate

after_success:
  - |
    if [[ "$PYTEST_COVERAGE" = 1 ]]; then
      set -e
      # Add last TOXENV to $PATH.
      PATH="$PWD/.tox/${TOXENV##*,}/bin:$PATH"
      coverage combine
      coverage xml
      coverage report -m
      bash <(curl -s https://codecov.io/bash) -Z -X gcov -X coveragepy -X search -X xcode -X gcovout -X fix -f coverage.xml -n $TOXENV-$TRAVIS_OS_NAME
    fi

notifications:
  irc:
    channels:
      - "chat.freenode.net#pytest"
    on_success: change
    on_failure: change
    skip_join: true
  email:
    - pytest-commit@python.org
cache: false
