# Jobs only for pull requests.
# Keep the steps in sync with .github/workflows/main.yml.
name: PR only

on:
  pull_request:
    branches:
      - my-master

jobs:
  tests:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        name: [
          "mypy-diff",
        ]

        # include:
        #   - name: "mypy-diff"
        #     python: "3.8"
        #     os: ubuntu-latest
        #     tox_env: "mypy-diff"

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 2000
    - run: git fetch --tags origin
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}

    # Caching.
    - name: set PY_CACHE_KEY
      run: echo "::set-env name=PY_CACHE_KEY::$(python -c 'import hashlib, sys;print(hashlib.sha256(sys.version.encode()+sys.executable.encode()).hexdigest())')"
    - name: Cache .tox
      uses: actions/cache@v1
      with:
        path: ${{ github.workspace }}/.tox/${{ matrix.tox_env }}
        key: tox|${{ matrix.tox_env }}|${{ env.PY_CACHE_KEY }}|${{ hashFiles('tox.ini') }}|${{ hashFiles('setup.*') }}
    - name: Cache .pre-commit
      if: (matrix.tox_env == 'linting_ci')
      uses: actions/cache@v1
      with:
        path: ~/.cache/pre-commit
        key: pre-commit|${{ env.PY_CACHE_KEY }}|${{ hashFiles('.pre-commit-config.yaml') }}

    - name: Install tox / version information
      env:
        PIP_DISABLE_PIP_VERSION_CHECK: "1"
      run: |
        python -m pip --version
        python -m pip install git+https://github.com/blueyed/tox@master
        python -m pip list

    - name: Setup tox environment
      run: python -m tox --notest -v --durations -e ${{ matrix.tox_env }}

    - name: Test
      env:
        PYTEST_ADDOPTS: "-ra --durations=50 ${{ matrix.pytest_addopts }}"
        COLUMNS: "120"
      run: "${{ matrix.script_prefix }} tox -e ${{ matrix.tox_env }}"

    - name: Report coverage
      if: always() && (contains(matrix.tox_env, '-coverage'))
      env:
        CODECOV_TOKEN: d79f3a85-e675-4d75-8f55-3d0e4a99ebe8
      run: "bash .ci/report-coverage.sh -n '${{ matrix.name }}' -F 'GHA,${{ runner.os }}'"
